### ISSUE TITLE
Ash twin warp pad doesn't work correctly

### ISSUE THREAD

**Issue by gintamaben** [PacificEngine/OW_CommonResources#2]
Ash twin warp pad on twin tower doesn't teleport to Ash twin core as it supposed to, but instead it teleport character to get stuck on terrain

This is mod loader log when that happened

[OWML]: Error: NullReferenceException: Object reference not set to an instance of an object
Stacktrace: PacificEngine.OW_CommonResources.Game.State.WarpPad.onWarp (NomaiWarpPlatform caller, PacificEngine.OW_CommonResources.Game.Resource.Position+HeavenlyBodies parentBody, OWRigidbody warpedBody, NomaiWarpPlatform startPlatform, NomaiWarpPlatform targetPlatform) (at <9343de0fd74e484a864e4f3f74483d3a>:0)
PacificEngine.OW_CommonResources.Game.State.WarpPad+<>c__DisplayClass40_1.<updateLists>b__0 (OWRigidbody warpedObject, NomaiWarpPlatform start, NomaiWarpPlatform target) (at <9343de0fd74e484a864e4f3f74483d3a>:0)
NomaiWarpPlatform.ReceiveWarpedBody (OWRigidbody body, NomaiWarpPlatform startPlatform) (at <6981773f82a4486a9b48d7b04937b6e2>:0)
(wrapper dynamic-method) NomaiWarpReceiver.DMD<NomaiWarpReceiver::ReceiveWarpedBody>(NomaiWarpReceiver,OWRigidbody,NomaiWarpPlatform)
NomaiWarpPlatform.TransmitWarpedBody (OWRigidbody body) (at <6981773f82a4486a9b48d7b04937b6e2>:0)
NomaiWarpPlatform.FixedUpdate () (at <6981773f82a4486a9b48d7b04937b6e2>:0)

**Comment by salomj** [comment]
I'll take a look at it. I'm pretty close to releasing a big update, which includes a lot of teleportation work (I'm giving the ability to freely teleport and reorient planets), and I've been giving Ash Twin some TLC during it, as there are several bugs in Ash Twin related to this for some reason, nowhere else though.

Is this when you are inside your ship or outside of your ship?

**Comment by salomj** [comment]
Please update to the latest release, and let me know if you are still having this issue.

**Comment by Owen013** [comment]
This still seems to be an issue...

**Comment by salomj** [comment]
Ah! Literally only happens if the randomizer mod is not installed. If the randomizer mods is installed, but disabled, this does not happen.

**Comment by salomj** [comment]
Fixed in this commit: https://github.com/PacificEngine/OW_CommonResources/commit/2ec735351445dbea911e52396d32eae081f18520 , so it will be fixed on the next release.

**Comment by salomj** [comment]
This should be fixed by v0.4.6. Please verify.

**Comment by Owen013** [comment]
It's fixed on my end!
