### ISSUE TITLE
Extreme collision problems on Brittle Hollow

### ISSUE THREAD

**Issue by Owen013** [PacificEngine/OW_CommonResources#3]
This mod is causing me to have some pretty serious collision problems on Brittle Hollow. Sometimes I float above the surface, other times I sink into it. I think the collision isn't synced up with the visuals, because I can't enter the escape pod through the door but I can enter right above the door and stand inside the ceiling. I uninstalled and reinstalled the mod to confirm that the mod is causing it. I don't have this issue if the mod is uninstalled or disabled.
![Outer Wilds Screenshot 2021 12 22 - 20 00 41 97](https://user-images.githubusercontent.com/96493201/147172178-06b7b2a0-c2b1-4b04-bfca-1adf39dae6ee.png)
![Outer Wilds Screenshot 2021 12 22 - 20 00 45 90](https://user-images.githubusercontent.com/96493201/147172181-d32106d3-1cc0-4614-9cc9-49b6d06f6148.png)

**Comment by salomj** [comment]
Hmm... I had tested this several times and thought it was fixed. I wonder if I did something to break it again. Are you using the Randomizer mod on top of this?

**Comment by salomj** [comment]
Looks like the issue occurs because I am reparenting things, which I forgot about that. When I delete the reparenting code, everything works fine. https://github.com/PacificEngine/OW_CommonResources/commit/e827ab9c1b1d81bda3f2c0e0ff6ec1f53dbccd69

**Comment by salomj** [comment]
Please update to the latest and confirm if this bug is still an issue.

**Comment by Owen013** [comment]
Seems to be fixed now! By the way, no, I was not using the randomizer mod.
