### ISSUE TITLE
No anglerfish in Dark Bramble + Stranger rafts don't spawn in their normal location

### ISSUE THREAD

**Issue by Owen013** [PacificEngine/OW_CommonResources#4]
I've tested this with and without PacificEngine's Common Resources to ensure that it's causing this. With PacificEngine installed, there are no anglerfish anywhere in Dark Bramble.

Without PacificEngine:
![Outer Wilds Screenshot 2021 12 23 - 16 24 53 63](https://user-images.githubusercontent.com/96493201/147292665-c6871e99-6e81-44e1-9088-d9010190ebd3.png)

With PacificEngine:
![Outer Wilds Screenshot 2021 12 23 - 16 19 44 85](https://user-images.githubusercontent.com/96493201/147292688-ec97e7be-7f60-4482-a035-fa1ca2c200b5.png)

Also, I noticed another bug(although not as big a deal as the lack of anglerfish). With PacificEngine installed, it seems that the rafts on the Stranger are spawning just slightly off of their intended spawn point?

Without PacificEngine:
![Outer Wilds Screenshot 2021 12 23 - 16 14 20 38](https://user-images.githubusercontent.com/96493201/147292805-8d3151b1-0c60-463c-97eb-b1def8948374.png)

With PacificEngine:
![Outer Wilds Screenshot 2021 12 23 - 16 18 21 81](https://user-images.githubusercontent.com/96493201/147292847-22cde0d3-8f1e-44da-97de-725a92341b5f.png)

**Comment by salomj** [comment]
Hmm... Not sure what happened with the Anglerfish, but the rafts shifting like that is definitely due to a precision issue.

**Comment by salomj** [comment]
Look like the fix for Anglerfish is to not move unloaded objects.

**Comment by salomj** [comment]
It seems to have something to do with the rafts not being loaded when setting the stranger's position. If I set my spawn location to be inside the stranger, the rafts are always in the right location. Even if I move the stranger, the rafts are in the right location.

**Comment by salomj** [comment]
Further, it seems specific to the rafts. If I have the stranger not change location, but have the rafts try to map to the strangers location, there is still an issue. Only if I explicitly tell the rafts to not try and update their location does this issue seem to be solved.

**Comment by salomj** [comment]
Looks like that might also be related to the rafts being disabled.

**Comment by salomj** [comment]
Okay, I believe I fixed both issues with 0.4.4, please update to the latest and try again.

**Comment by Owen013** [comment]
Both fixed! Good work!
