### ISSUE TITLE
Model rocket and white hole (MINOR) issues

### ISSUE THREAD

**Issue by Owen013** [PacificEngine/OW_CommonResources#5]
I found a few minor issues while playing the game. Firstly, using the model rocket for the first time in a loop causes it to teleport into the rock wall behind you! This only happens the first time you use it, it works as it's supposed to on any subsequent attempt.
Without PacificEngine: https://youtu.be/aRW-Kh42z_g
With PacificEngine: https://youtu.be/zFGozGbBrGM

Also, when you leave the vessel to go to the surface of the Eye, the white hole doesn't close behind you.
Without PacificEngine: ![Outer Wilds Screenshot 2021 12 24 - 10 46 12 52](https://user-images.githubusercontent.com/96493201/147365207-4ee9e0c6-bc95-4d57-bc39-591bcd946c86.png)
With PacificEngine:  ![Outer Wilds Screenshot 2021 12 24 - 09 35 49 74](https://user-images.githubusercontent.com/96493201/147365214-1c62af87-ca5d-4312-914c-d22d94ec4118.png)

**Comment by salomj** [comment]
Huh, that is a odd one. I guess I never turned around when going to the eye, I also never tried using the model rocket, I figured if it appears in place, it was in place.. I'll check it out tomorrow.

**Comment by salomj** [comment]
I think this is related to the WarpPad NPE, which would explain why I've never seen it before.

**Comment by salomj** [comment]
The model ship issue, only happens with the randomizer mod off, same with the white hole. The Whitehole issue is fixed with the Warppad NPE fix. https://github.com/PacificEngine/OW_CommonResources/issues/2

**Comment by salomj** [comment]
Model ship will be fixed by this code: https://github.com/PacificEngine/OW_CommonResources/commit/36b7dd53464517c37586bf90dbd4a4b4adaa957f

**Comment by salomj** [comment]
This should be fixed by v0.4.6. Please verify.

**Comment by Owen013** [comment]
Yup!
