### ISSUE TITLE
Owlks are leaning?!

### ISSUE THREAD

**Issue by Owen013** [PacificEngine/OW_CommonResources#6]
This one's a funny one. The owlks in the dream world are, for some reason, _leaning_ if Common Resources is enabled!
Without Common Resources: ![OuterWildsEchoes NotSidewaysOwlk](https://user-images.githubusercontent.com/96493201/147416938-7cadb7e9-38f5-40f3-8782-86dc9eff6e45.png)
With Common Resources: ![OuterWildsEchoes SidewaysOwlk1](https://user-images.githubusercontent.com/96493201/147416947-1512978e-0e35-4310-b7fc-868f517e2efe.png)

**Comment by salomj** [comment]
Should be fixed by: https://github.com/PacificEngine/OW_CommonResources/commit/0ff3cb10467ea33027c4142c3d7158b72de95a82

**Comment by salomj** [comment]
This should be fixed by v0.4.6. Please verify.

**Comment by Owen013** [comment]
Yep, appears to be fixed!
