### ISSUE TITLE
Sky shutter satellite is backwards?

### ISSUE THREAD

**Issue by Owen013** [PacificEngine/OW_CommonResources#7]
The satellite that you can take pictures from in the village seems to be backward and slightly misaligned with Common Resources installed. I have tested this with and without Common Resources, the satellite is normal without the mod.

**Comment by salomj** [comment]
The alignment I have a fix for, as it looks like I forgot to update the probe after a reference plane shift.

The direction of the satellite is determined by `AlignWithTargetBody`. So I am unsure why it is backwards.

**Comment by salomj** [comment]
It is worth noting that it isn't the only object misaligned. Sun Station is also facing the wrong direction. It appears as if `AlignWithTargetBody` Only sets the pointing vector, and not the rotation of the body.

**Comment by salomj** [comment]
This means that Interloper and Attlerock are also probably misaligned.

**Comment by salomj** [comment]
Should be fixed in the latest, please verify.

**Comment by Owen013** [comment]
Hmm... still seems to be backwards. The primary tool button is taking a picture from the back and the secondary is taking a picture from the front, the opposite of how it should be.

**Comment by salomj** [comment]
This issue should now be fixed with latest changes.
