### ISSUE TITLE
white hole station is gone

### ISSUE THREAD

**Issue by Talchyr** [PacificEngine/OW_CommonResources#8]
or at least, not where it's supposed to be

rough position on wakeup with common resources off:
![2022-01-14 17_40_35-Window](https://user-images.githubusercontent.com/3684173/149604177-55f02cd7-4a55-421f-bd8f-743bc908b789.png)

rough position on wakeup with common resources on:
![2022-01-14 17_42_18-Window](https://user-images.githubusercontent.com/3684173/149604182-19d59a96-c335-4aea-9fc5-113746728f5f.png)

**Comment by salomj** [comment]
Hmm... That seems new. I think I'll push the thing I was thinking about awhile ago, where the planet modification is by default off, unless another mod makes adjustments to planet positions.

**Comment by salomj** [comment]
This was fixed awhile ago, and I never closed it
