### ISSUE TITLE
Orbital probe cannon debris flies through atmosphere

### ISSUE THREAD

**Issue by xen-42** [PacificEngine/OW_CommonResources#9]
The pieces of debris do not have the proper orbits. After the probe breaks up initially the pieces are moved to match the orbit of the rest of the cannon once they pass behind the planet. With common resources they are put into the wrong place and given eccentric orbits.

**Comment by salomj** [comment]
Huh, I was wondering what they did for that. Because debris in real life would not behave the way it does in the base game.

**Comment by xen-42** [comment]
Yeah, actually its not even that they are moved to new positions, there are two separate sets of objects: the debris pieces that fall apart at the start of the loop and then the debris pieces that orbit behind the cannon. When it activates the pieces that orbit the planet the old pieces stick around for a second. If you get to the ship straight away and go to Giant's Deep on the map view you can catch it when it happens

**Comment by salomj** [comment]
Hmm... I guess that makes things easier.
